### ISSUE TITLE
Fix content of tabs without spacing classes

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#111]
Ako hotfix na zobrazenie contentu som pouzil spacing utility classes. Zhodli sme sa, ze to nie vhodne a malo by sa to spravit systemovejsie.

Dotknute casti:

### ex-twitter

- https://github.com/keboola/kbc-ui/commit/040fa5ace6d4d92c19704bedae8140634188807b

### ex-facebook

- https://github.com/keboola/kbc-ui/commit/1620ce5dafd293afdadba2965238b114d255d807
- tu mi to ale pride celkom ok, ak ten select spravime sucastou formulara, nemusi to vyzera najlepsie

### ex-adform

- https://github.com/keboola/kbc-ui/commit/cdcc5be916d34046af8a17b099db9af0dbc8f073

### eventy

- https://github.com/keboola/kbc-ui/commit/708dbc59cd7263859f31287a9d9af7a2aa0801e4

### orchestration job detail

- suvisi s eventami
- https://github.com/keboola/kbc-ui/commit/3d04790dbcd9784ac120adb59f46dfd4585b5cbe

### job detail

- https://github.com/keboola/kbc-ui/commit/9b16ca8cee90c655a47e85b53ff26eb3c3d1dc60
- suvisi s eventami

Komponenty ex-twitter a ex-adform su pripad, kde by stacilo pridat horizontalny spacing na `tab-content`, ma to vsak par much:
- odsadilo by to vsetky tabulky (ktore mame full width)
- pridalo by to dalsi spacing to modalov (kde je teraz spacing skrz `modal-body`

Predtym to bolo vyriesene takto https://github.com/keboola/indigo-ui/commit/1eda686fc253175050bdb983d0476c82e3de6cbc, co sa mi nepaci z viac dovodov:

- ostylovana `row` classa (toho by sme sa nemali chytat, rozbija to potom layout, ked chcem pouzit `row`)
- aplikovane styles na `*`

**Comment by ujovlado** [comment]
@janmichek ako by si to riesil?

Jedna z moznosti co mi napada je pridat to naozaj na `tab-content` a nasledne dat zaporny pre `table` a pre `modal-body`, t.j. nieco ako:

```css
.tab-content {
  padding-left: 1em;
  padding-right: 1em;
  table, .table {
    margin-left: -1em;
    margin-right: -1em;
  }
}
.modal-body {
  .tab-content {
    padding-left: 0;
    padding-right: 0;
  }
}
```

... s tou tabulkou to ale asi fungovat nebude
